name: Deploy Sphinx Documentation to GitHub Pages

on:
  push:
    branches:
      - main # Oder dein Haupt-Branch, z.B. master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    environment: # Hinzugef端gt
      name: github-pages # Hinzugef端gt
      url: ${{ steps.deployment.outputs.page_url }} # Hinzugef端gt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Stelle sicher, dass dies mit deiner lokalen Python-Version 端bereinstimmt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme m2r2 sphinx-autodoc-typehints

      - name: Build Sphinx documentation
        run: |
          cd docs/sphinx
          make html

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/sphinx/build/html/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
